// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1pmCxZx8jMTdlIzblFt8flR0C1i61goc',
    appId: '1:719434665410:web:771d2ab948398d46919a5b',
    messagingSenderId: '719434665410',
    projectId: 'authentication-e8b7e',
    authDomain: 'authentication-e8b7e.firebaseapp.com',
    storageBucket: 'authentication-e8b7e.firebasestorage.app',
    measurementId: 'G-0NLM92T3TQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZaeeroP5x58OeOVyObcObVmmNsc2i2rE',
    appId: '1:719434665410:android:30580d7fbf17025b919a5b',
    messagingSenderId: '719434665410',
    projectId: 'authentication-e8b7e',
    storageBucket: 'authentication-e8b7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUOmYLVUTDv5EauLbB63oxlmeNstzN18w',
    appId: '1:719434665410:ios:925b4f58788bc131919a5b',
    messagingSenderId: '719434665410',
    projectId: 'authentication-e8b7e',
    storageBucket: 'authentication-e8b7e.firebasestorage.app',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUOmYLVUTDv5EauLbB63oxlmeNstzN18w',
    appId: '1:719434665410:ios:925b4f58788bc131919a5b',
    messagingSenderId: '719434665410',
    projectId: 'authentication-e8b7e',
    storageBucket: 'authentication-e8b7e.firebasestorage.app',
    iosBundleId: 'com.example.todoTask',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1pmCxZx8jMTdlIzblFt8flR0C1i61goc',
    appId: '1:719434665410:web:1e685d7c8dedf968919a5b',
    messagingSenderId: '719434665410',
    projectId: 'authentication-e8b7e',
    authDomain: 'authentication-e8b7e.firebaseapp.com',
    storageBucket: 'authentication-e8b7e.firebasestorage.app',
    measurementId: 'G-LVTXB1V963',
  );
}
